% test
v = [1  2  1; ...
        2  3  5; ...
        3  1  3; ...
        1  4  1; ...
        2  3  5; ...
        3  2  4]; size(v);

w = [.1  0.8  .1; ...
        .2  0.7  .1; ...
        .3  0.6  .1; ...
        .1  0.5  .4; ...
        .2  0.4  .4; ...
        .3  0.3  .4]; size(w);



m=[wmean(v,w,'arithmetic') wmean(v,w,'geometric') wmean(v,w,'harmonic') wmean(v,w,'square-root')]

e=wmean(v,w,'blah')